# Generated by Django 4.2.2 on 2023-06-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otp",
            name="access",
        ),
        migrations.RemoveField(
            model_name="otp",
            name="refresh",
        ),
        migrations.AddField(
            model_name="otp",
            name="code",
            field=models.IntegerField(default=1212),
            preserve_default=False,
        ),
    ]
