# Generated by Django 4.2.2 on 2023-06-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitedetail",
            options={"verbose_name_plural": "Site details"},
        ),
        migrations.AlterField(
            model_name="sitedetail",
            name="fb",
            field=models.CharField(
                default="https://facebook.com", max_length=300, verbose_name="Facebook"
            ),
        ),
        migrations.AlterField(
            model_name="sitedetail",
            name="ig",
            field=models.CharField(
                default="https://instagram.com",
                max_length=300,
                verbose_name="Instagram",
            ),
        ),
        migrations.AlterField(
            model_name="sitedetail",
            name="tw",
            field=models.CharField(
                default="https://twitter.com", max_length=300, verbose_name="Twitter"
            ),
        ),
        migrations.AlterField(
            model_name="sitedetail",
            name="wh",
            field=models.CharField(
                default="https://wa.me/2348133831036",
                max_length=300,
                verbose_name="Whatsapp",
            ),
        ),
    ]
