# Generated by Django 4.2.2 on 2023-06-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0002_alter_sitedetail_options_alter_sitedetail_fb_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitedetail",
            name="email",
            field=models.EmailField(default="kayprogrammer1@gmail.com", max_length=254),
        ),
    ]
